<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Abhishek" name="Parallel_Test_1" tests="1" failures="0" timestamp="22 Dec 2017 17:59:46 GMT" time="0.236" errors="0">
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="Automation2018.AutoShow.LearnTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Automation2018.AutoShow.BaseTest.beforeTest(BaseTest.java:24)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="Automation2018.AutoShow.LearnTest">
    <skipped/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="test1" time="0.195" classname="Automation2018.AutoShow.LearnTest">
    <skipped/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Parallel_Test_1 -->
